# Generated by Django 2.0 on 2018-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
