# Generated by Django 2.0 on 2018-05-07 04:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20180506_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('pub_time', models.DateTimeField(default=datetime.datetime.now)),
                ('up_num', models.IntegerField()),
                ('down_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('pub_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=120)),
                ('pic_url', models.CharField(max_length=240)),
                ('title', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('like_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('view_num', models.IntegerField()),
                ('soruce', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Media'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Media'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.User'),
        ),
    ]
